services:
  app:
    build: .
    ports:
      - "8000:8000"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase3
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


