# Generated by Django 5.0.4 on 2024-06-18 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product_stripe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.sale')),
            ],
        ),
    ]
